# Generated by Django 2.1.7 on 2019-10-16 10:57

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('fightmate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
