# Generated by Django 2.1.7 on 2019-11-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightmate', '0006_add_mixing_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fight',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='fight',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='user',
            name='longitude',
        ),
        migrations.AddField(
            model_name='discipline',
            name='grapple',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discipline',
            name='kick',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discipline',
            name='punch',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fight',
            name='rate_fighter_1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fight',
            name='rate_fighter_2',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
