# Generated by Django 2.1.7 on 2019-11-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightmate', '0008_add_city_and_country_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
