# Generated by Django 2.1.7 on 2019-11-25 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fightmate', '0009_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField()),
                ('url', models.CharField(max_length=100)),
                ('bio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pictures', to='fightmate.Bio')),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
    ]
