# Generated by Django 2.1.7 on 2019-11-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fightmate', '0010_pictures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bios', to=settings.AUTH_USER_MODEL),
        ),
    ]
